# Generated by Django 2.1.1 on 2019-01-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavySetalSlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('strength', models.FloatField(max_length=10)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NiIronSlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('strength', models.FloatField(max_length=10)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RedMud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('strength', models.FloatField(max_length=10)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SteelSlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('strength', models.FloatField(max_length=10)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VantaiSlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('strength', models.FloatField(max_length=10)),
                ('rate', models.FloatField(max_length=10)),
            ],
        ),
    ]
