# Generated by Django 2.1.1 on 2019-01-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_heavysetalslag_niironslag_redmud_steelslag_vantaislag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavysetalslag',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='niironslag',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redmud',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steelslag',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vantaislag',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
